"""Initial schema

Revision ID: 8c31597c8830
Revises: 
Create Date: 2025-11-22 14:31:46.011616

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8c31597c8830'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('budget_tier', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('travel_style', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('local_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_server_id'), 'trips', ['server_id'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('budget_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('local_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_items_server_id'), 'budget_items', ['server_id'], unique=False)
    op.create_index(op.f('ix_budget_items_trip_id'), 'budget_items', ['trip_id'], unique=False)
    op.create_table('days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('local_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_days_server_id'), 'days', ['server_id'], unique=False)
    op.create_index(op.f('ix_days_trip_id'), 'days', ['trip_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('local_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_server_id'), 'notes', ['server_id'], unique=False)
    op.create_index(op.f('ix_notes_trip_id'), 'notes', ['trip_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('day_id', sa.Uuid(), nullable=False),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('local_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_day_id'), 'activities', ['day_id'], unique=False)
    op.create_index(op.f('ix_activities_server_id'), 'activities', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_server_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_day_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_notes_trip_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_server_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_days_trip_id'), table_name='days')
    op.drop_index(op.f('ix_days_server_id'), table_name='days')
    op.drop_table('days')
    op.drop_index(op.f('ix_budget_items_trip_id'), table_name='budget_items')
    op.drop_index(op.f('ix_budget_items_server_id'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_server_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
